service: BREWOPTIX-PO-EMAIL-API # Purchase order API

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}
  environment: ${self:custom.environment}
  iamRoleStatements:
    - ${self:custom.iamRoleStatements}
    - ${self:provider.sqsRoleStatements}
  sqsRoleStatements:
    Effect: Allow
    Action:
      - sqs:SendMessage
      - sqs:GetQueueUrl
      - sqs:ListQueues
    Resource:
      - arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-email-transmitter

custom: ${file(../config.yaml)}

package:
  include:
    - ../api_utils.py
    - ../api_constants.py
    - ../common.py
    - ../../log_config.py
    - ../../logging_api.py
    - ../auth.py
    - ../../data_common/*
    - ../../data_dynamodb/*
    - ../../data_dynamodb/repository/*

functions:
  send_email_on_purchase_order:
    handler: handler.send_email_on_purchase_order
    name: ${self:provider.stage}-${self:service}-send-email-on-purchase-order
    description: Trigger sqs to send an email on purchase order sns notification
    timeout: 300
    environment:
      Q_NAME_EMAIL_TRANSMITTER: ${self:provider.stage}-email-transmitter
      PO_EMAIL_TEMPLATE_NAME: purchase_order_email_template
    events:
      - sns: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-purchase-orders

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-prune-plugin