service: BREWOPTIX-TABLES-COPIER-FN

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${file(../../../config.${self:provider.stage}.json):REGION}
  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:*:*:*"

custom:
  pythonRequirements:
    noDeploy: []    # https://github.com/UnitedIncome/serverless-python-requirements/issues/241#issuecomment-421355568
    dockerizePip: true
    fileName: ./requirements.txt

functions:
  copy_tables:
    handler: handler.copy_tables
    name: ${self:provider.stage}-${self:service}-copy-tables
    description: Copy items from src to dest tables
    timeout: 900

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
