service: BREWOPTIX-SUPPLIERS-API

provider: 
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}
  environment: ${self:custom.environment}
  iamRoleStatements:
    - ${self:custom.iamRoleStatements}
    - ${self:provider.snsRoleStatements}
    - ${self:provider.s3UploadStatements}
  apiGateway:
    restApiId:
      'Fn::ImportValue': BrewOptix-${self:provider.stage}-ApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': BrewOptix-${self:provider.stage}-ApiGateway-rootResourceId
  snsRoleStatements:
    Effect: Allow
    Action:
      - sns:Publish
    Resource:
      - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-suppliers
      - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-users
  s3UploadStatements:
    Effect: Allow
    Action:
      - s3:PutObject
    Resource:
      - 'arn:aws:s3:::${self:provider.environment.S3_UPLOADS_BUCKET_NAME}/*'

custom: ${file(../config.yaml)}

# It is not possible to reference files on directory levels above serverless.yml directly when working in AWS Lambda
# So, we either have to install these additional files as pip packages or `include` them to the package explicitly
# Included python files would be available parallel to serverless.yml and needs to be imported in this structure
# For example:
# fdc_data_dynamodb is present two levels above this serverless.yml, but in common.py it can be imported from cur dir.
package:
  include:
    - ../api_utils.py
    - ../api_constants.py
    - ../common.py
    - ../../log_config.py
    - ../../logging_api.py
    - ../auth.py
    - ../../data_common/*
    - ../../data_dynamodb/*
    - ../../data_dynamodb/repository/*

functions:
  add_supplier:
    handler: handler.add_supplier
    name: ${self:provider.stage}-${self:service}-add-supplier
    description: Add a new supplier
    timeout: 20
    events:
      - http:
          path: suppliers
          method: post
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  modify_supplier:
    handler: handler.modify_supplier
    name: ${self:provider.stage}-${self:service}-modify-supplier
    description: Update a supplier
    timeout: 20
    events:
      - http:
          path: suppliers
          method: put
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  get_supplier:
    handler: handler.get_by_id
    name: ${self:provider.stage}-${self:service}-get-supplier-by-id
    description: Get a supplier using entity_id
    timeout: 20
    events:
      - http:
          path: suppliers/{entity_id}
          method: get
          cors: ${self:custom.corsStatements}
          integration: lambda
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}
          request:
            parameters:
              paths:
                entity_id: true

  delete_supplier:
    handler: handler.delete_by_id
    name: ${self:provider.stage}-${self:service}-delete-supplier-by-id
    description: Delete a supplier using entity_id
    timeout: 20
    events:
      - http:
          path: suppliers/{entity_id}
          method: delete
          cors: ${self:custom.corsStatements}
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}
          request:
            parameters:
              paths:
                entity_id: true

  get_every_supplier:
    handler: handler.get_every_supplier
    name: ${self:provider.stage}-${self:service}-get-every-supplier
    description: Get every supplier
    timeout: 20
    events:
      - http:
          path: suppliers
          method: get
          cors: ${self:custom.corsStatements}
          integration: lambda
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  add_user_to_supplier:
    handler: handler.add_user_to_supplier
    name: ${self:provider.stage}-${self:service}-add-user-to-supplier
    description: Add a new or existing user to a supplier
    timeout: 120
    events:
      - http:
          path: suppliers/users
          method: post
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  delete_user_in_supplier:
    handler: handler.delete_user_in_supplier
    name: ${self:provider.stage}-${self:service}-delete-user-in-supplier
    description: Delete a user under an entity_id
    timeout: 20
    events:
      - http:
          path: suppliers/users/{user_id}
          method: delete
          cors: ${self:custom.corsStatements}
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}
          request:
            parameters:
              paths:
                user_id: true

  get_all_users_in_supplier:
    handler: handler.get_all_users_in_supplier
    name: ${self:provider.stage}-${self:service}-get-all-users-in-supplier
    description: Handle GET all user profiles under a supplier
    timeout: 20
    events:
      - http:
          path: suppliers/users
          method: get
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  process_supplier_save:
    handler: handler.process_supplier_save
    name: ${self:provider.stage}-${self:service}-process-supplier-save
    description: Process supplier saves
    timeout: 300
    events:
      - sns: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-suppliers

resources:
  Resources:
    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'obj saves are sent to this topic'
        TopicName: ${self:provider.stage}-suppliers

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-prune-plugin
