service: BREWOPTIX-SOCIAL-API

provider: 
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}
  environment: ${self:custom.environment}
  iamRoleStatements:
    - ${self:custom.iamRoleStatements}
    - ${self:provider.snsRoleStatements}
  apiGateway:
    restApiId:
      'Fn::ImportValue': BrewOptix-${self:provider.stage}-ApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': BrewOptix-${self:provider.stage}-ApiGateway-rootResourceId
  snsRoleStatements:
    Effect: Allow
    Action:
      - sns:Publish
    Resource:
      - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-suppliers
      - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-distributors
      - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-users

custom: ${file(../config.yaml)}

# It is not possible to reference files on directory levels above serverless.yml directly when working in AWS Lambda
# So, we either have to install these additional files as pip packages or `include` them to the package explicitly
# Included python files would be available parallel to serverless.yml and needs to be imported in this structure
# For example:
# fdc_data_dynamodb is present two levels above this serverless.yml, but in common.py it can be imported from cur dir.
package:
  include:
    - ../api_utils.py
    - ../api_constants.py
    - ../common.py
    - ../../log_config.py
    - ../../logging_api.py
    - ../auth.py
    - ../../data_common/*
    - ../../data_dynamodb/*
    - ../../data_dynamodb/repository/*

functions:
  social_auth:
    handler: handler.social_auth
    name: ${self:provider.stage}-${self:service}-social-auth
    description: Handle social authentication request
    timeout: 20
    events:
      - http:
          path: social-auth
          method: post
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda

  social_signin:
    handler: handler.social_signin
    name: ${self:provider.stage}-${self:service}-social-signin
    description: Handle social signin
    timeout: 20
    events:
      - http:
          path: social-signin
          method: post
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda

  social_signup:
    handler: handler.social_signup
    name: ${self:provider.stage}-${self:service}-social-signup
    description: Handle social signup
    timeout: 20
    events:
      - http:
          path: social-signup
          method: post
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-prune-plugin
