service: BREWOPTIX-DISTRIBUTORS-API

provider: 
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}
  environment: ${self:custom.environment}
  iamRoleStatements:
    - ${self:custom.iamRoleStatements}
    - ${self:provider.snsRoleStatements}
  apiGateway:
    restApiId:
      'Fn::ImportValue': BrewOptix-${self:provider.stage}-ApiGateway-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': BrewOptix-${self:provider.stage}-ApiGateway-rootResourceId
  snsRoleStatements:
    Effect: Allow
    Action:
      - sns:Publish
    Resource:
      - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-distributors
      - arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-users

custom: ${file(../config.yaml)}

# It is not possible to reference files on directory levels above serverless.yml directly when working in AWS Lambda
# So, we either have to install these additional files as pip packages or `include` them to the package explicitly
# Included python files would be available parallel to serverless.yml and needs to be imported in this structure
# For example:
# fdc_data_dynamodb is present two levels above this serverless.yml, but in common.py it can be imported from cur dir.
package:
  include:
    - ../api_utils.py
    - ../api_constants.py
    - ../common.py
    - ../../log_config.py
    - ../../logging_api.py
    - ../auth.py
    - ../../data_common/*
    - ../../data_dynamodb/*
    - ../../data_dynamodb/repository/*

functions:
  get_every_distributor:
    handler: handler.get_every_distributor
    name: ${self:provider.stage}-${self:service}-get-every-distributor
    description: Get every distributor
    timeout: 20
    events:
      - http:
          path: distributors
          method: get
          cors: ${self:custom.corsStatements}
          integration: lambda
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  add_distributor:
    handler: handler.add_distributor
    name: ${self:provider.stage}-${self:service}-add-entity
    description: Add a new distributor
    timeout: 20
    events:
      - http:
          path: distributors
          method: post
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  modify_distributor:
    handler: handler.modify_distributor
    name: ${self:provider.stage}-${self:service}-modify-entity
    description: Update a distributor
    timeout: 20
    events:
      - http:
          path: distributors
          method: put
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  get_distributor:
    handler: handler.get_by_id
    name: ${self:provider.stage}-${self:service}-get-by-id
    description: Get a distributor using entity_id
    timeout: 20
    events:
      - http:
          path: distributors/{entity_id}
          method: get
          cors: ${self:custom.corsStatements}
          integration: lambda
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}
          request:
            parameters:
              paths:
                entity_id: true

  delete_distributor:
    handler: handler.delete_by_id
    name: ${self:provider.stage}-${self:service}-delete-by-id
    description: Delete a distributor using entity_id
    timeout: 20
    events:
      - http:
          path: distributors/{entity_id}
          method: delete
          cors: ${self:custom.corsStatements}
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}
          request:
            parameters:
              paths:
                entity_id: true

  add_user_to_distributor:
    handler: handler.add_user_to_distributor
    name: ${self:provider.stage}-${self:service}-add-user-to-distributor
    description: Add a new or existing user to a distributor
    timeout: 120
    events:
      - http:
          path: distributors/users
          method: post
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  delete_user_in_distributor:
    handler: handler.delete_user_in_distributor
    name: ${self:provider.stage}-${self:service}-delete-user-in-distributor
    description: Delete a user in distributor
    timeout: 20
    events:
      - http:
          path: distributors/users/{user_id}
          method: delete
          cors: ${self:custom.corsStatements}
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}
          request:
            parameters:
              paths:
                user_id: true

  get_all_users_in_distributor:
    handler: handler.get_all_users_in_distributor
    name: ${self:provider.stage}-${self:service}-get-all-users-in-distributor
    description: Handle GET all user profiles under a distributor
    timeout: 20
    events:
      - http:
          path: distributors/users
          method: get
          cors: ${self:custom.corsStatements}
          response:
            headers:
              Content-Type: "'application/json'"
            template: $input.path('$.body')
          integration: lambda
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:BREWOPTIX-AUTH-${self:provider.stage}.apiGatewayAuthorizer}

  process_distributor_save:
    handler: handler.process_distributor_save
    name: ${self:provider.stage}-${self:service}-process-distributor-save
    description: Process distributor saves
    timeout: 300
    events:
      - sns: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:provider.stage}-distributors

resources:
  Resources:
    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'obj saves are sent to this topic'
        TopicName: ${self:provider.stage}-distributors


plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-prune-plugin
